CREATE TABLE RECIPES
(
    RECIPE_ID           INTEGER AUTO_INCREMENT PRIMARY KEY,
    RECIPE_NAME         VARCHAR(255) NOT NULL,
    RECIPE_TIME         ENUM ('QUICK', 'MEDIUM', 'LONG'),
    RECIPE_DIFFICULTY   ENUM ('EASY', 'MEDIUM', 'HARD'),
    RECIPE_DESCRIPTION  TEXT,
    RECIPE_INSTRUCTIONS TEXT
);

CREATE TABLE INGREDIENTS
(
    INGREDIENT_ID   INTEGER AUTO_INCREMENT PRIMARY KEY,
    INGREDIENT_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE RECIPE_INGREDIENTS
(
    RECIPE_ID     INTEGER NOT NULL,
    INGREDIENT_ID INTEGER NOT NULL,
    QUANTITY      INTEGER NOT NULL,
    OPTIONAL      BOOLEAN NOT NULL,

    CONSTRAINT FK_RECIPE_ID FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES (RECIPE_ID),
    CONSTRAINT FK_INGREDIENT_ID FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS (INGREDIENT_ID)
);

CREATE TABLE TAGS
(
    TAG_ID   INTEGER AUTO_INCREMENT PRIMARY KEY,
    TAG_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE INGREDIENT_TAG
(
    INGREDIENT_ID INTEGER,
    TAG_ID        INTEGER,

    CONSTRAINT FK_INGREDIENT_TAG_INGREDIENT_ID FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS (INGREDIENT_ID),
    CONSTRAINT FK_INGREDIENT_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAGS (TAG_ID)
);

CREATE TABLE PANTRY_ZONE
(
    PANTRY_ID  INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME       VARCHAR(255) NOT NULL,
    MIN_TEMP   INTEGER      NOT NULL,
    MAX_TEMP   INTEGER      NOT NULL,
    MIN_HUM    INTEGER      NOT NULL,
    MAX_HUM    INTEGER      NOT NULL,
    MIN_BRIGHT INTEGER      NOT NULL,
    MAX_BRIGHT INTEGER      NOT NULL
);

CREATE TABLE SENSOR_DATA
(
    DATA_ID     INTEGER AUTO_INCREMENT PRIMARY KEY,
    PANTRY_ID   INTEGER NOT NULL,
    TIME_STAMP  TIMESTAMP,
    SENSOR_VALUE       INTEGER NOT NULL,
    SENSOR_TYPE ENUM ('humidity', 'temperature', 'brightness'),

    CONSTRAINT FK_PANTRY_ID FOREIGN KEY (PANTRY_ID) REFERENCES PANTRY_ZONE (PANTRY_ID)
);

CREATE TABLE END_USER
(
    USER_ID           INTEGER AUTO_INCREMENT PRIMARY KEY,
    USER_NAME         VARCHAR(255) NOT NULL,
    USER_EMAIL        VARCHAR(255) NOT NULL,
    USER_CITY         VARCHAR(255) NOT NULL,
    USER_STATE_REGION VARCHAR(255) NOT NULL,
    USER_ZIP          VARCHAR(255) NOT NULL,
    USER_COUNTRY      VARCHAR(255) NOT NULL
);

CREATE TABLE USER_PREFERENCE
(
    USER_ID INTEGER NOT NULL,
    TAG_ID  INTEGER NOT NULL,
    "LIKE"  BOOLEAN NOT NULL,

    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES END_USER (USER_ID),
    CONSTRAINT FK_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAGS (TAG_ID)
);

CREATE TABLE PANTRY_ZONE_INGREDIENT
(
    INGREDIENT_ID INTEGER NOT NULL,
    PANTRY_ID     INTEGER NOT NULL,

    AMOUNT        INTEGER NOT NULL,
    DATE_ENTERED  DATE,

    CONSTRAINT FK_PANTRY_ZONE_INGREDIENT_INGREDIENT_ID FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS (INGREDIENT_ID),
    CONSTRAINT FK_PANTRY_ZONE_INGREDIENT_PANTRY_ID FOREIGN KEY (PANTRY_ID) REFERENCES PANTRY_ZONE (PANTRY_ID)
);
