CREATE TABLE RECIPES
(
    ID           INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME         VARCHAR(255) NOT NULL,
    TIME         ENUM ('QUICK', 'MEDIUM', 'LONG'),
    DIFFICULTY   ENUM ('EASY', 'MEDIUM', 'HARD'),
    DESCRIPTION  TEXT,
    INSTRUCTIONS TEXT
);

CREATE TABLE INGREDIENTS
(
    ID   INTEGER AUTO_INCREMENT PRIMARY KEY,
    INGREDIENT_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE RECIPE_INGREDIENTS
(
    RECIPE_ID     INTEGER NOT NULL,
    INGREDIENT_ID INTEGER NOT NULL,
    QUANTITY      INTEGER NOT NULL,
    OPTIONAL      BOOLEAN NOT NULL,

    CONSTRAINT FK_RECIPE_ID FOREIGN KEY (RECIPE_ID) REFERENCES RECIPES (ID),
    CONSTRAINT FK_INGREDIENT_ID FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS (ID)
);

CREATE TABLE TAGS
(
    ID   INTEGER AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE INGREDIENT_TAG
(
    INGREDIENT_ID INTEGER,
    TAG_ID        INTEGER,

    CONSTRAINT FK_INGREDIENT_TAG_INGREDIENT_ID FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS (ID),
    CONSTRAINT FK_INGREDIENT_TAG_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAGS (ID)
);

CREATE TABLE PANTRY_ZONE
(
    ID  INTEGER AUTO_INCREMENT PRIMARY KEY,
    USER_ID         INTEGER      NOT NULL;
    NAME            VARCHAR(255) NOT NULL,
    MAX_TEMP        INTEGER      NOT NULL,
    MIN_HUM         INTEGER      NOT NULL,
    MIN_TEMP        INTEGER      NOT NULL,
    MAX_HUM         INTEGER      NOT NULL,
    MIN_BRIGHT      INTEGER      NOT NULL,
    MAX_BRIGHT      INTEGER      NOT NULL,

    CONSTRAINT FK_PANTRY_USER_ID FOREIGN KEY (USER_ID) REFERENCES END_USERS (ID)
);

CREATE TABLE SENSOR_DATA
(
    ID                  INTEGER AUTO_INCREMENT PRIMARY KEY,
    PANTRY_ZONE_ID      INTEGER NOT NULL,
    TIME_STAMP          TIMESTAMP,
    SENSOR_VALUE        INTEGER NOT NULL,
    SENSOR_TYPE ENUM ('HUMIDITY', 'TEMPERATURE', 'BRIGHTNESS'),

    CONSTRAINT FK_PANTRY_ID FOREIGN KEY (PANTRY_ZONE_ID) REFERENCES PANTRY_ZONE (ID)
);

CREATE TABLE END_USER
(
    ID           INTEGER AUTO_INCREMENT PRIMARY KEY,
    USERNAME     VARCHAR(255) NOT NULL,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    EMAIL        VARCHAR(255) NOT NULL,
    CITY         VARCHAR(255) NOT NULL,
    STATE_REGION VARCHAR(255) NOT NULL,
    ZIP          VARCHAR(255) NOT NULL,
    COUNTRY      VARCHAR(255) NOT NULL
);

CREATE TABLE USER_PREFERENCE
(
    USER_ID     INTEGER NOT NULL,
    TAG_ID      INTEGER NOT NULL,
    "LIKE"      BOOLEAN NOT NULL,

    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES END_USER (ID),
    CONSTRAINT FK_TAG_ID FOREIGN KEY (TAG_ID) REFERENCES TAGS (TAG_ID)
);

CREATE TABLE PANTRY_ZONE_INGREDIENT
(
    INGREDIENT_ID INTEGER NOT NULL,
    PANTRY_ID     INTEGER NOT NULL,
    AMOUNT        INTEGER NOT NULL,
    DATE_ENTERED  DATE,

    CONSTRAINT FK_PANTRY_ZONE_INGREDIENT_INGREDIENT_ID FOREIGN KEY (INGREDIENT_ID) REFERENCES INGREDIENTS (ID),
    CONSTRAINT FK_PANTRY_ZONE_INGREDIENT_PANTRY_ID FOREIGN KEY (PANTRY_ID) REFERENCES PANTRY_ZONE (ID)
);
